language: java
os: linux
dist: focal
jdk:
  - openjdk16
script: mvn clean test
install: true
notifications:
  email:
    recipients:
      - "dmulloy2@live.com"
    on_success: change
    on_failure: always
